name: CI/CD Workflow

on:
    pull_request:
        branches:
            - master

jobs:
    lint:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - name: Install Linter
              run: pip install flake8
            - name: Run Linter
              run: flake8 .

    build-and-push:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Docker registry login
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags:
                     nelututriesit/cicd:1
                     nelututriesit/cicd:2
                     nelututriesit/cicd:3
